class ChallengeError(Exception):
    """Raised when an error occurs."""
